# Generated by Django 5.2.8 on 2026-01-08 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_created_at_company_description_company_owner_and_more'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('company', 'title', 'description'), name='unique_job_per_company'),
        ),
    ]
